[build.environment]
  GO_VERSION = "1.25.1"

  [build]
  command = "cp $(go env GOROOT)/lib/wasm/wasm_exec.js . && env GOOS=js GOARCH=wasm go build -o go-pong.wasm github.com/ngolebiewski/go-pong"
  
  publish = "."